# Data
path: C:\Users\dokov\Documents\Uni\HiWi\ISW\HiwiISW\keytooldataset
train: images/train  # train images (relative to 'path')
val: images/val  # val images (relative to 'path')

# Keypoints
kpt_shape: [3, 3]  # [number of keypoints, number of dim]
flip_idx: [0, 1, 2]

# Classes
names:
  0: keytool